%% Set up cryophilic point labeling
% An example script with annotations
%%

existsAndDefault('fromScratch', false);
%% LOADING FILES FROM DISK
% loading specific files by name
ts1 = tic;
existsAndDefault('marcmac', false);
if (marcmac)
    basedir =  '~/Documents/lab data/n2cryo/';
else
    basedir = '\\labnas1\Share\David\Extracted\Spatial\N2\18-23GradientC15\OutputFiles\';
end
d = dir([basedir '*.bin']);
nfiles = 24;
if (fromScratch)
    nfiles = min(nfiles, length(d));
    for j = 1:nfiles
        fnames{j} = [basedir d(j).name]; %#ok<SAGROW>
    end
    %fnames = {[basedir '20090226_N2g15_1823_tracks.bin'], [basedir '20090226_w1a_N2g15_1823_tracks.bin']};

    % load any track longer than 50 points
    minpts = 50;

    % this code snippet loads the files if we haven't already loaded them, but
    % otherwise skips them; that way we can change the script and rerun it
    % without having to reload the files
    if (~exist('cryo', 'var'))
        cryo = ExperimentSet.fromFiles(fnames{:}, 'minpts', minpts);
    end

    %% STITCH TRACKS
    % sometimes we miss a frame, so let's stitch together tracks that are close
    % by

    frameDiff = 3; % stitch together tracks if first ended 3 or fewer frames before second started
    maxDist = 7; % stitch together tracks if first ended within 7 pixels of second's start

    % For the script, I am executing this function with interactive off, but if
    % you set interactive to true, it will show you each potential stitch and
    % let you decide whether or not to stitch it
    cryo.executeExperimentFunction('stitchTracks', frameDiff, maxDist, 'interactive', false);

    %% CLEAN UP TRACKS
    % get rid of any tracks that don't go anywhere

    % create an EsetCleaner object

    ecl = ESetCleaner();

    % now let's look at the autogenerated report
    % let's get rid of all tracks less than 750 points and speed less than 0.4
    % pixels per second
    ecl.minPts = 750;
    ecl.minSpeed = 0.9;

    %ecl.getReport(cryo);

    % the following code just forces the figures to appear in the example documentation
    %{
    for j = 1:3
        figure(j);
        snapnow; 
    end
    %}

    % we've already shown the report, so we don't need to have it ask us first,
    % for the purposes of this script;  generally a good idea to leave this
    % enabled
    ecl.askFirst = false; 

    ecl.clean(cryo);
    disp('done with loading, stitching and cleaning');
    toc(ts1)
    ts1 = tic;
   % save (fullfile(basedir, 'marcmatfile.mat'), 'cryo');
    mkdir (fullfile(basedir, 'matfiles'));
    cryo.toMatFiles(fullfile(basedir, 'matfiles','cryo_spatial'));
    disp('saved file');
    toc(ts1)
    fromScratch = false;
else
    if (~exist('cryo', 'var'))
        ts1 = tic;
     
        %load (fullfile(basedir, 'marcmatfile.mat'));
        cryo = ExperimentSet.fromMatFiles(fullfile(basedir, 'matfiles','cryo_spatial'));
        disp ('loaded eset from mat file');
        toc(ts1)
    end
end

%% Segmenting Tracks
% separate tracks into runs and reorientations
trimrect = [800 20 2100 1920];
trimtime = [];
existsAndDefault('retrim', true);
if (retrim)
    disp('trimming tracks');
    ts1 = tic;
    cryo.executeExperimentFunction('trimTracks', trimtime, trimrect);
    resegment = true;
    retrim = false;
    disp ('done');
    toc(ts1);
end
existsAndDefault('resegment', true);
if (resegment)
    disp ('segmenting tracks');
    wso = WormSegmentOptions;
    ts1 = tic;
    cryo.executeExperimentFunction('segmentTracks', wso);
    disp ('done');
    toc(ts1)
    resegment = false;
end

%alltr = [cryo.expt.track];
%alltr.plotPath('displacement');

%%
% analyze results

fignum = 0;
fignum = fignum + 1; figure(fignum); clf(fignum);

tx = deg2rad(0:30:330);
reorate = cryo.makeReorientationHistogram('theta', tx, 'polar', true, 'r2d', true);
revom = cryo.makeReorientationHistogram('theta', tx, 'polar', true, 'r2d', true, 'turnsequence', [1 -1]);
revrev = cryo.makeReorientationHistogram('theta', tx, 'polar', true, 'r2d', true, 'turnsequence', [1 2]);
justom = cryo.makeReorientationHistogram('theta', tx, 'polar', true, 'r2d', true, 'turnsequence', -1);
justblip = cryo.makeReorientationHistogram('theta', tx, 'polar', true, 'r2d', true, 'turnsequence', 0);
allothers = reorate - (revom + revrev + justom + justblip);
plot (rad2deg(tx), reorate, rad2deg(tx), revom, rad2deg(tx), revrev, rad2deg(tx), justom,...
    rad2deg(tx), justblip, rad2deg(tx), allothers, 'linewidth', 2); ylim([0 0.3])
title ('reorientation rate vs. instantaneous angle');
xlabel ('heading (degrees)');
ylabel ('reo rate (1/min)');
legend ('all', 'reversal omega', 'reversal reversal', 'just omega', 'just a blip', 'all others');
