function tLightOnPlot(X1, meany1, X2, new1)
%CREATEFIGURE(X1,MEANY1,X2,NEW1)
%  X1:  time since light on vector
%  MEANY1: derivated quantity that you want to plot v. time vector (ie head
%  sweep angle)
%  X2:  time since light on vector
%  NEW1:  target light vector

%  Auto-generated by MATLAB on 13-Sep-2010 10:09:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[40 60 80],...
    'Position',[0.268888888888889 0.262798789712557 0.527657657657658 0.517836611195159],...
    'FontSize',12);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 200]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[40 80]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,meany1,'Parent',axes1,'LineWidth',3,'DisplayName','meany');

% Create xlabel
xlabel('Time (seconds)','FontSize',16);

% Create ylabel
ylabel('Maximum headsweep angle','FontSize',16);

% Create axes
axes2 = axes('Parent',figure1,'YTickLabel',{'Off','On'},'YTick',[0 1],...
    'YAxisLocation','right',...
    'Position',[0.268888888888889 0.262798789712557 0.527657657657658 0.517836611195159],...
    'FontSize',12,...
    'ColorOrder',[0 0.5 0;1 0 0;0 0.75 0.75;0.75 0 0.75;0.75 0.75 0;0.25 0.25 0.25;0 0 1],...
    'Color','none');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 200]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1]);
hold(axes2,'all');

% Create plot
plot(X2,new1,'Parent',axes2,'LineWidth',3,'Color',[1 0 0],...
    'DisplayName','new');

% Create ylabel
ylabel({'Light',''},'VerticalAlignment','cap','FontSize',14);

