function plotVarByLT(x1, Y1, eti1, lt1)
%plotVarByLT(X1,Y1,ETI,LT1) plots a variable as a function of time with
%light value plot above 
%  X1:  vector of variable x data
%  Y1:  vector of variable y data
%  ETI1:  vector of interpolated time data
%  LT1:  vector of light data data

%  Auto-generated by MATLAB on 27-Jul-2010 14:40:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'0','500','1000','1500','2000','2500'},...
    'XTick',[0 500 1000 1500 2000 2500],...
    'Position',[0.156195462478185 0.282092572384081 0.715532286212914 0.234106131719591],...
    'FontSize',12);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(x1,Y1,'Parent',axes1,'LineWidth',2,...
    'Color',[0.400000005960464 0.400000005960464 1],...
    'DisplayName','turning rate');

% Create ylabel
ylabel(input('What is variable name y axis: ','s'),'FontSize',14);

% Create xlabel
xlabel('Time(s)','FontSize',14);

% Create axes
axes2 = axes('Parent',figure1,'XTickLabel','',...
    'Position',[0.156195462478185 0.557787572987528 0.715532286212915 0.174393852498434],...
    'FontSize',12);
% %Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 2400]);
box(axes2,'on');
hold(axes2,'all');

% Create title
title(input('What is title of graph: ','s'),'FontSize',14);

% Create plot
plot(eti1,lt1,'Parent',axes2,'LineWidth',2,...
    'Color',[1 0.400000005960464 0.400000005960464],...
    'DisplayName','target light');

% Create ylabel
ylabel(['Target',sprintf('\n'),'light value'],'FontSize',14);

